language: node_js
node_js:
  - "12.16"

services:
  - docker

branches:
  only:
  - master

install:
  - npm install
  - npm run build
  - docker build -t $docker_hub_user/money-tracker:$TRAVIS_BUILD_NUMBER .
  
after_success:
  - docker login --username=$docker_hub_user --password=$docker_hub_pass
  - docker push $docker_hub_user/money-tracker:$TRAVIS_BUILD_NUMBER

deploy:
  - provider: script
    skip_cleanup: true
    script: source deploy/deploy.sh
    on:
      branch: master