language: node_js
node_js:
- '14.13'
os: linux
dist: focals

env:
- IMAGE=minicreative/money-tracker:$TRAVIS_BUILD_NUMBER

branches:
  only:
  - main

services:
- docker

install:
- sudo snap install kubectl --classic

script:
- npm install
- npm run build:full
- docker build -t $IMAGE .

before_deploy:
- mkdir ${HOME}/.kube
- echo "$KUBECONFIG_ENC" | base64 --decode > ${HOME}/.kube/config
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $IMAGE
- envsubst < kube.yaml > kube-merged.yaml

deploy:
- provider: script
  skip_cleanup: true
  script: kubectl apply -f kube-merged.yaml
  on:
    branch: main
