language: node_js
node_js:
- '12.16'

services:
- docker

branches:
  only:
  - master

install:
- npm install
- npm run build
- docker build -t $docker_hub_user/money-tracker:$TRAVIS_BUILD_NUMBER .

script:
- echo "No tests for now"

after_success:
- docker login --username=$docker_hub_user --password=$docker_hub_pass
- docker push $docker_hub_user/money-tracker:$TRAVIS_BUILD_NUMBER

before_deploy:
- ssh-keyscan -H $deploy_host >> $HOME/.ssh/known_hosts
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: ssh $deploy_user@$deploy_host /home/$deploy_user/deploy.sh
  on:
    branch: master
