apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: money-tracker
  template:
    metadata:
      labels:
        app: money-tracker
    spec:
      containers:
      - name: main
        image: $IMAGE
        ports:
        - containerPort: 3001
          protocol: TCP
        env:
        - name: mt_port
          value: '3001'
        envFrom:
        - secretRef:
            name: money-tracker-secret
        - configMapRef:
            name: money-tracker-config
---
apiVersion: v1
kind: Service
metadata:
  name: money-tracker
spec:
  type: ClusterIP
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: money-tracker
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: money-tracker-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - money.tomasroy.com
    secretName: money-tracker-tls-cert
  rules:
  - host: money.tomasroy.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: money-tracker
            port:
              number: 3001