---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

resources:
  - name: money-tracker
    type: git
    source: &repo-source
      uri: https://github.com/minicreative/money-tracker
      branch: master
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
  - name: Install dependencies
    plan:
      - get: money-tracker
        trigger: true
      - get: dependency-cache
  - name: Run tests
    plan:
      - get: money-tracker
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]
      - task: run the test suite
        file: money-tracker/deploy/test.yml