---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: money-tracker
  - name: dependency-cache

run:
  path: money-tracker/deploy/test.sh