name: Build NodeJS & Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Install dependencies
      run: npm install
    - name: Build the app
      run: npm run build:full
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
    - name: Build and Push the Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ vars.docker_name }}:${{ github.sha }}, ${{ vars.docker_name }}:latest
  publish:
    environment: Production
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.kube_config }}
    - uses: actions/checkout@v3
    - name: Update Kubernetes deployment
      run: kubectl set image "deployment/${{ vars.kube_deployment }}" "main=${{ vars.docker_name }}:${{ github.sha }}"
